version: '3'
services:
  tabroom:
    container_name: mason-dev
    build:
      context: .
      dockerfile: Dockerfile
    image: mason-dev:latest
    restart: always
    ports:
      - 8000:80
    volumes:
      - ${TABROOM_WEB:-/www/tabroom/web}:/www/tabroom/web:rw
      - ${TABROOM_WEB_MASON:-/www/tabroom/web/mason}:/www/tabroom/web/mason:rw
      - ${TABROOM_WEB_TMP:-/www/tabroom/web/tmp}:/www/tabroom/web/tmp:rw
      - ${TABROOM_PROFILES:-/www/profiles}:/www/profiles:rw
      - ${TABROOM_LOGS:-/var/log/apache2}:/var/log/apache2:rw
      - ${TABROOM_GENERAL:-/etc/tabroom/General.dev.pm}:/www/tabroom/web/lib/Tab/General.pm:ro
      - ./conf/dev.tabroom.com.conf:/etc/apache2/sites-enabled/dev.tabroom.com.conf:ro
      - ./conf/envvars:/etc/apache2/envvars:ro
      - ./conf/apache2.conf:/etc/apache2/apache2.conf:ro
      - ./conf/perl.conf:/etc/apache2/mods-enabled/perl.conf:ro
      - ./conf/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "api.dev.tabroom.com:host-gateway"
      - "legacyapi.dev.tabroom.com:host-gateway"
