#
# Docker compose file that will run a local staging instance given the
# appropriate array of apache configurations. I apologize that it's so many
# configs required locally but that's life running a legacy service sometimes.

version: '3'
services:
  tabroom:
    container_name: mason
    image: mason:latest
    restart: always
    ports:
      - 9000:80
    volumes:
      - /www/tabroom/web:/www/tabroom/web:rw
      - /www/profiles:/www/profiles:rw
      - /var/log/apache2:/var/log/apache2:rw
      - /etc/tabroom/General.pm:/www/tabroom/web/lib/Tab/General.pm:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "staging-api.tabroom.com:host-gateway"
